polybar

diff --git a/.config/grub/install b/.config/grub/install
--- a/.config/grub/install
+++ b/.config/grub/install
@@ -1,24 +1,24 @@
 #!/bin/bash
-if test -f "/etc/default/grub" then
+if test -e "/etc/default/grub" ; then
     cp /etc/default/grub default/grub.bak
     echo "Backuped your /etc/default/grub in ./default/grub.bak"
-    rm /etc/default/grub
+    rm /etc/default/grub;
 fi
-ln -s default/grub /etc/default/grub
-if [[ $? != 0 ]] then
+ln -s "$(pwd)/default/grub" /etc/default/grub
+if [[ $? != 0 ]] ; then
     echo "Configuration failed"
-    if test -f "default/grub" then
-        cp default/grub /etc/default/grub;
-        if [[ $? == 0 ]] then
-            echo "Restored /etc/default/grub"
+    if test -f "default/grub" ; then
+        cp default/grub.bak /etc/default/grub;
+        if [[ $? == 0 ]] ; then
+            echo "Restored /etc/default/grub";
         fi
     fi
-    exit
+    exit;
 fi
-for $file in "grub.d" do
-    ln -s grub.d/$file /etc/grub.d/$file
-    if [[ $? != 0 ]] then
-        echo "Failed to symlink grub.d/$file"
+for file in ./grub.d/* ; do
+    ln -s "$(pwd)/$file" "/etc/$file"
+    if [[ $? != 0 ]] ; then
+        echo "Failed to symlink grub.d/$file";
     fi
 done
 echo "Finished"
